version: "3"

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    ports: 
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./Backend/PersonalBlog
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    depends_on:
      - db
    environment:
      - POSTGRES_DB=personalblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: personalblog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: